### PR TITLE
Test reporter

### LINKED ISSUE #27: Add `result_path` feature to extract result content

### LINKED ISSUE #30: Differentiate between testnet and mainnet using different indexers
https://github.com/ringecosystem/xapi-offchain/blob/569648f0e9624b03b2d5d842af14954b886e5811/packages/publisher-client/src/command/start.ts#L76-L77

https://github.com/ringecosystem/xapi-offchain/blob/569648f0e9624b03b2d5d842af14954b886e5811/packages/reporter-client/src/command/start.ts#L51-L52

### LINKED ISSUE #31: Reporter check error message include assertion skip report again
```
Smart contract panicked: assertion failed: Threshold: required 3, but got 2\n    at assert (build/ormp_aggregator.js:2229)\n
```

### PR DESCRIPTION
**Pull request by fewensa**
fix #27
fix #31
fix #30 

related
- #32

### CODE REVIEW

File: packages/reporter-client/src/main.ts [hunk 1]
```diff
@@ -41,6 +34,14 @@ program
     [],
   )
   .action(async (options) => {
+    if (!options.nearAccount) {
+      logger.error('missing near account, please add --near-account or set env.XAPI_NEAR_ACCOUNT');
+      process.exit(1);
+    }
+    if (!options.nearPrivateKey) {
+      logger.error('missing near account, please add --near-private-key or set env.XAPI_NEAR_PRIVATE_KEY');
```
Comment (jiguantong) [inline packages/reporter-client/src/main.ts:42]: missing near private key
